spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountshield
    username: shield
    password: shield_pw
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080